#!/bin/bash

echo "  # Downstream"
for i in {1..33}; do 
echo "  - platform: mqtt"
echo "    name: \"Cable Modem Downstream ${i} Power\""
echo "    unique_id: \"modemsignals_downstream_${i}_power\""
echo "    state_topic: \"homeassistant/sensor/modemsignals/downstream/${i}\""
echo "    unit_of_measurement: 'dBmV'"
echo "    value_template: \"{{ value_json.Power }}\""
echo "    json_attributes_topic: \"homeassistant/sensor/modemsignals/downstream/${i}\""
echo "  - platform: mqtt"
echo "    name: \"Cable Modem Downstream ${i} SNR\""
echo "    unique_id: \"modemsignals_downstream_${i}_snr\""
echo "    state_topic: \"homeassistant/sensor/modemsignals/downstream/${i}\""
echo "    unit_of_measurement: 'dB'"
echo "    value_template: \"{{ value_json.SNR_MER }}\""
echo "  - platform: mqtt"
echo "    name: \"Cable Modem Downstream ${i} Corrected\""
echo "    unique_id: \"modemsignals_downstream_${i}_corrected\""
echo "    state_topic: \"homeassistant/sensor/modemsignals/downstream/${i}\""
echo "    unit_of_measurement: 'Corrected Errors'"
echo "    value_template: \"{{ value_json.Corrected }}\""
echo "  - platform: mqtt"
echo "    name: \"Cable Modem Downstream  ${i} Uncorrectable\""
echo "    unique_id: \"modemsignals_downstream_${i}_uncorrectable\""
echo "    state_topic: \"homeassistant/sensor/modemsignals/downstream/${i}\""
echo "    unit_of_measurement: 'Uncorrectable Errors'"
echo "    value_template: \"{{ value_json.Uncorrectable }}\""
echo ""
done

echo "  # Upstream"
for i in {1..4}; do 
echo "  - platform: mqtt"
echo "    name: \"Cable Modem Upstream ${i} Power\""
echo "    unique_id: \"modemsignals_upstream_${i}_power\""
echo "    state_topic: \"homeassistant/sensor/modemsignals/upstream/${i}\""
echo "    unit_of_measurement: 'dBmV'"
echo "    value_template: \"{{ value_json.Power }}\""
echo "    json_attributes_topic: \"homeassistant/sensor/modemsignals/upstream/${i}\""
echo ""
done
